### PR TITLE
Adding terraform for very basic AKS Cluster

### PR DESCRIPTION
**Pull request by karl-engineering-clouds**
Added a super basic AKS cluster in terraform. Will get back to it tomorrow morning to finish off.

# TODO 

- [ ] Add second AKS Cluster in Secondary Region
- [ ] Add Ingress Controller installation/configuration (Optional) @guidemetothemoon - Do we need this or shall we just expose services as we need?
- [ ] Add Traffic Manager with confiuration to point to Clusters
- [ ] Add Helm/kubectl apply for workloads to deploy.

### CODE REVIEW

**Comment by guidemetothemoon** [comment]
Regarding Ingress Controller, @irishtechie , I don't think we need it for the purpose of the demo. I'm at least trying to keep it simple and will use HTTP Application Routing add-on in AKS - then it's super easy to quickly expose an app for demo purposes without using much time on setting up an Ingress Controller.

**Comment by karl-engineering-clouds** [comment]
Ok cool. I can add that into the terraform I think. 

I will finish off in morning.

**Comment by guidemetothemoon** [comment]
Thank you for the contribution so far, Karl, highly appreciated! I'll hopefully create a PR today/tomorrow as well.
Also, for the recording purposes and due to the time pressure as a quick workaround we can always set it up manually but finalize all the resources in the repo with IaC templates prior to the session release in December.

**Comment by karl-engineering-clouds** [comment]
Good idea! My brain is broken today 😂😂!

**Pull request closed without merging**
